name: Test and Linter

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test-and-lint:
    name: Run Tests and Linter
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v

    - name: Run linter
      run: make lint

    - name: Run tests
      run: make test

    - name: Run tests with coverage
      run: make test-coverage
