name: test and linter

on:
  push:
    branches: [ main, master ]
jobs:
  test-and-lint:
    name: Run Tests and Linter
    runs-on: ubuntu-latest

    - name: Run linter
      run: make lint

    - name: Run tests
      run: make test

    - name: Run tests with coverage
      run: make test-coverage
